-- Drop table

-- DROP TABLE public."CSDB_HangupCauses"

CREATE TABLE public."CSDB_HangupCauses" (
	id serial NOT NULL,
	"ItutQ850Code" int4 NULL,
	"SipEquiv" int4 NULL,
	"Enumeration" varchar(255) NULL,
	"Cause" varchar(255) NULL,
	"Description" text NULL,
	"createdAt" timestamptz NOT NULL,
	"updatedAt" timestamptz NOT NULL,
	CONSTRAINT "CSDB_HangupCauses_pkey" PRIMARY KEY (id)
)
WITH (
	OIDS=FALSE
) ;

/* INSERT QUERY NO: 1 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
0, NULL, 'UNSPECIFIED', 'Unspecified. No other cause codes applicable.', 'This is usually given by the router when none of the other codes apply. This cause usually occurs in the same type of situations as cause 1'
);

/* INSERT QUERY NO: 2 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
1, '404', 'UNALLOCATED_NUMBER', 'Unallocated (unassigned) number [Q.850 value 1]', 'This cause indicates that the called party cannot be reached because'
);

/* INSERT QUERY NO: 3 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
2, '404', 'NO_ROUTE_TRANSIT_NET', 'No route to specified transit network (national use) [Q.850]', 'This cause indicates that the equipment sending this cause has received a request to route the call through a particular transit network'
);

/* INSERT QUERY NO: 4 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
3, '404', 'NO_ROUTE_DESTINATION', 'No route to destination [Q.850]', 'This cause indicates that the called party cannot be reached because the network through which the call has been routed does not serve the destination desired. This cause is supported on a network dependent basis.'
);

/* INSERT QUERY NO: 5 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
6, NULL, 'CHANNEL_UNACCEPTABLE', 'channel unacceptable [Q.850]', 'This cause indicates that the channel most recently identified is not acceptable to the sending entity for use in this call.'
);

/* INSERT QUERY NO: 6 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
7, NULL, 'CALL_AWARDED_DELIVERED', 'call awarded', ' being delivered in an established channel [Q.850]'
);

/* INSERT QUERY NO: 7 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
16, NULL, 'NORMAL_CLEARING', 'normal call clearing [Q.850]', 'This cause indicates that the call is being cleared because one of the users involved in the call has requested that the call be cleared. Under normal situations'
);

/* INSERT QUERY NO: 8 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
17, '486', 'USER_BUSY', 'user busy [Q.850]', 'This cause is used to indicate that the called party is unable to accept another call because the user busy condition has been encountered. This cause value may be generated by the called user or by the network. In the case of user determined user busy it is noted that the user equipment is compatible with the call.'
);

/* INSERT QUERY NO: 9 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
18, '408', 'NO_USER_RESPONSE', 'no user responding [Q.850]', 'This cause is used when a called party does not respond to a call establishment message with either an alerting or connect indication within the prescribed period of time allocated.'
);

/* INSERT QUERY NO: 10 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
19, '480', 'NO_ANSWER', 'no answer from user (user alerted) [Q.850]', 'This cause is used when the called party has been alerted but does not respond with a connect indication within a prescribed period of time. Note - This cause is not necessarily generated by Q.931 procedures but may be generated by internal network timers.'
);

/* INSERT QUERY NO: 11 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
20, '480', 'SUBSCRIBER_ABSENT', 'subscriber absent [Q.850]', 'This cause value is used when a mobile station has logged off'
);

/* INSERT QUERY NO: 12 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
21, '603', 'CALL_REJECTED', 'call rejected [Q.850]', 'This cause indicates that the equipment sending this cause does not wish to accept this call'
);

/* INSERT QUERY NO: 13 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
22, '410', 'NUMBER_CHANGED', 'number changed [Q.850]', 'This cause is returned to a calling party when the called party number indicated by the calling party is no longer assigned'
);

/* INSERT QUERY NO: 14 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
23, '410', 'REDIRECTION_TO_NEW_DESTINATION', ' ', 'This cause is used by a general ISUP protocol mechanism that can be invoked by an exchange that decides that the call should be set-up to a different called number. Such an exchange can invoke a redirection mechanism'
);

/* INSERT QUERY NO: 15 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
25, '483', 'EXCHANGE_ROUTING_ERROR', ' ', 'This cause indicates that the destination indicated by the user cannot be reached'
);

/* INSERT QUERY NO: 16 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
27, '502', 'DESTINATION_OUT_OF_ORDER', 'destination out of order [Q.850]', 'This cause indicates that the destination indicated by the user cannot be reached because the interface to the destination is not functioning correctly. The term "not functioning correctly" indicates that a signal message was unable to be delivered to the remote party; e.g. a physical layer or data link layer failure at the remote party'
);

/* INSERT QUERY NO: 17 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
28, '484', 'INVALID_NUMBER_FORMAT', 'invalid number format (address incomplete) [Q.850]', 'This cause indicates that the called party cannot be reached because the called party number is not in a valid format or is not complete.'
);

/* INSERT QUERY NO: 18 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
29, '501', 'FACILITY_REJECTED', 'facilities rejected [Q.850]', 'This cause is returned when a supplementary service requested by the user cannot be provide by the network.'
);

/* INSERT QUERY NO: 19 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
30, NULL, 'RESPONSE_TO_STATUS_ENQUIRY', 'response to STATUS INQUIRY [Q.850]', 'This cause is included in the STATUS message when the reason for generating the STATUS message was the prior receipt of a STATUS INQUIRY.'
);

/* INSERT QUERY NO: 20 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
31, '480', 'NORMAL_UNSPECIFIED', 'normal', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 21 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
34, '503', 'NORMAL_CIRCUIT_CONGESTION', 'no circuit/channel available [Q.850]', 'This cause indicates that there is no appropriate circuit/channel presently available to handle the call.'
);

/* INSERT QUERY NO: 22 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
38, '503', 'NETWORK_OUT_OF_ORDER', 'network out of order [Q.850]', 'This cause indicates that the network is not functioning correctly and that the condition is likely to last a relatively long period of time e.g. immediately re-attempting the call is not likely to be successful.'
);

/* INSERT QUERY NO: 23 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
41, '503', 'NORMAL_TEMPORARY_FAILURE', 'temporary failure [Q.850]', 'This cause indicates that the network is not functioning correctly and that the condition is not likely to last a long period of time; e.g. the user may wish to try another call attempt almost immediately.'
);

/* INSERT QUERY NO: 24 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
42, '503', 'SWITCH_CONGESTION', 'switching equipment congestion [Q.850]', 'This cause indicates that the switching equipment generating this cause is experiencing a period of high traffic.'
);

/* INSERT QUERY NO: 25 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
43, NULL, 'ACCESS_INFO_DISCARDED', 'access information discarded [Q.850]', 'This cause indicates that the network could not deliver access information to the remote user as requested'
);

/* INSERT QUERY NO: 26 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
44, '503', 'REQUESTED_CHAN_UNAVAIL', 'requested circuit/channel not available [Q.850]', 'This cause is returned when the other side of the interface cannot provide the circuit or channel indicated by the requesting entity.'
);

/* INSERT QUERY NO: 27 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
45, NULL, 'PRE_EMPTED', ' ', ' '
);

/* INSERT QUERY NO: 28 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
47, NULL, ' ', 'resource unavailable', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 29 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
50, NULL, 'FACILITY_NOT_SUBSCRIBED', 'requested facility not subscribed [Q.850', 'This cause indicates that the user has requested a supplementary service'
);

/* INSERT QUERY NO: 30 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
52, '403', 'OUTGOING_CALL_BARRED', 'outgoing calls barred', 'This cause indicates that although the calling party is a member of the CUG for the outgoing CUG call'
);

/* INSERT QUERY NO: 31 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
54, '403', 'INCOMING_CALL_BARRED', 'incoming calls barred', 'This cause indicates that although the called party is a member of the CUG for the incoming CUG call'
);

/* INSERT QUERY NO: 32 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
57, '403', 'BEARERCAPABILITY_NOTAUTH', 'bearer capability not authorized [Q.850]', 'This cause indicates that the user has requested a bearer capability that is implemented by the equipment which generated this cause but the user is not authorized to use.'
);

/* INSERT QUERY NO: 33 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
58, '503', 'BEARERCAPABILITY_NOTAVAIL', 'bearer capability not presently available [Q.850]', 'This cause indicates that the user has requested a bearer capability which is implemented by the equipment which generated this cause but which is not available at this time.'
);

/* INSERT QUERY NO: 34 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
63, NULL, 'SERVICE_UNAVAILABLE', 'service or option not available', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 35 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
65, '488', 'BEARERCAPABILITY_NOTIMPL', 'bearer capability not implemented [Q.850]', 'This cause indicates that the equipment sending this cause does not support the bearer capability requested.'
);

/* INSERT QUERY NO: 36 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
66, NULL, 'CHAN_NOT_IMPLEMENTED', 'channel type not implemented [Q.850]', 'This cause indicates that the equipment sending this cause does not support the channel type requested'
);

/* INSERT QUERY NO: 37 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
69, '501', 'FACILITY_NOT_IMPLEMENTED', 'requested facility not implemented [Q.850]', 'This cause indicates that the equipment sending this cause does not support the requested supplementary services.'
);

/* INSERT QUERY NO: 38 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
79, '501', 'SERVICE_NOT_IMPLEMENTED', 'service or option not implemented', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 39 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
81, NULL, 'INVALID_CALL_REFERENCE', 'invalid call reference value [Q.850]', 'This cause indicates that the equipment sending this cause has received a message with a call reference which is not currently in use on the user-network interface.'
);

/* INSERT QUERY NO: 40 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
88, '488', 'INCOMPATIBLE_DESTINATION', 'incompatible destination [Q.850]', 'This cause indicates that the equipment sending this cause has received a request to establish a call which has low layer compatibility'
);

/* INSERT QUERY NO: 41 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
95, NULL, 'INVALID_MSG_UNSPECIFIED', 'invalid message', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 42 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
96, NULL, 'MANDATORY_IE_MISSING', 'mandatory information element is missing [Q.850]', 'This cause indicates that the equipment sending this cause has received a message which is missing an information element which must be present in the message before that message can be processed.'
);

/* INSERT QUERY NO: 43 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
97, NULL, 'MESSAGE_TYPE_NONEXIST', 'message type non-existent or not implemented [Q.850]', 'This cause indicates that the equipment sending this cause has received a message with a message type it does not recognize either because this is a message not defined of defined but not implemented by the equipment sending this cause.'
);

/* INSERT QUERY NO: 44 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
98, NULL, 'WRONG_MESSAGE', 'message not compatible with call state or message type non-existent or not implemented. [Q.850]', 'This cause indicates that the equipment sending this cause has received a message such that the procedures do not indicate that this is a permissible message to receive while in the call state'
);

/* INSERT QUERY NO: 45 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
99, NULL, 'IE_NONEXIST', 'Information element / parameter non-existent or not implemented [Q.850]', 'This cause indicates that the equipment sending this cause has received a message which includes information element(s)/parameter(s) not recognized because the information element(s)/parameter name(s) are not defined or are defined but not implemented by the equipment sending the cause. This cause indicates that the information element(s)/parameter(s) were discarded. However'
);

/* INSERT QUERY NO: 46 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
100, NULL, 'INVALID_IE_CONTENTS', 'Invalid information element contents [Q.850]', 'This cause indicates that the equipment sending this cause has received and information element which it has implemented; however'
);

/* INSERT QUERY NO: 47 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
101, NULL, 'WRONG_CALL_STATE', 'message not compatible with call state [Q.850]', 'This cause indicates that a message has been received which is incompatible with the call state.'
);

/* INSERT QUERY NO: 48 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
102, '504', 'RECOVERY_ON_TIMER_EXPIRE', 'recovery on timer expiry [Q.850]', 'This cause indicates that a procedure has been initiated by the expiration of a timer in association with error handling procedures. This is often associated with NAT problems. Ensure that "NAT Mapping Enable" is turned on in your ATA. If it is not NAT related it can sometimes be provider related'
);

/* INSERT QUERY NO: 49 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
103, NULL, 'MANDATORY_IE_LENGTH_ERROR', 'parameter non-existent or not implemented - passed on (national use) [Q.850]', 'This cause indicates that the equipment sending this cause has received a message which includes parameters not recognized because the parameters are not defined or are defined but not implemented by the equipment sending this cause. The cause indicates that the parameter(s) were ignored. In addition'
);

/* INSERT QUERY NO: 50 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
111, NULL, 'PROTOCOL_ERROR', 'protocol error', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 51 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
127, NULL, 'INTERWORKING', 'Interworking', ' unspecified [Q.850]'
);

/* INSERT QUERY NO: 52 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
487, '487', 'ORIGINATOR_CANCEL', ' ', ' '
);

/* INSERT QUERY NO: 53 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
500, NULL, 'CRASH', ' ', ' '
);

/* INSERT QUERY NO: 54 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
501, NULL, 'SYSTEM_SHUTDOWN', ' ', ' '
);

/* INSERT QUERY NO: 55 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
502, NULL, 'LOSE_RACE', ' ', ' '
);

/* INSERT QUERY NO: 56 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
503, NULL, 'MANAGER_REQUEST', ' ', 'This cause is used when you send an api command to make it hangup. For example uuid_kill <uuid>'
);

/* INSERT QUERY NO: 57 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
600, NULL, 'BLIND_TRANSFER', ' ', ' '
);

/* INSERT QUERY NO: 58 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
601, NULL, 'ATTENDED_TRANSFER', ' ', ' '
);

/* INSERT QUERY NO: 59 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
602, NULL, 'ALLOTTED_TIMEOUT', ' ', 'This cause means that the server canceled the call because the destination channel took too long to answer.'
);

/* INSERT QUERY NO: 60 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
603, NULL, 'USER_CHALLENGE', ' ', ' '
);

/* INSERT QUERY NO: 61 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
604, NULL, 'MEDIA_TIMEOUT', ' ', ' '
);

/* INSERT QUERY NO: 62 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
605, NULL, 'PICKED_OFF', ' ', 'This cause means the call was picked up by intercepting it from another extension (i.e. dialing **ext_number from another extension).'
);

/* INSERT QUERY NO: 63 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
606, NULL, 'USER_NOT_REGISTERED', ' ', 'This means you tried to originate a call to a SIP user who forgot to register.'
);

/* INSERT QUERY NO: 64 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
607, NULL, 'PROGRESS_TIMEOUT', ' ', 'See: progress_timeout'
);

/* INSERT QUERY NO: 65 */
INSERT INTO "CSDB_HangupCauses" ("ItutQ850Code", "SipEquiv", "Enumeration", "Cause", "Description")
VALUES
(
609, NULL, 'GATEWAY_DOWN', ' ', 'Gateway is down (not answering on OPTIONS or SUBSCRIBE)'
);

